import { useEffect, useState } from 'react';
import { useAuthStore } from '../store/auth';
import { LogOut, Search, Filter, MapPin, Clock, CheckCircle, XCircle, FileText, Image as ImageIcon, Copy, FileOutput, Navigation } from 'lucide-react';
import { format } from 'date-fns';
import Map3D from '../components/Map3D';
import jsPDF from 'jspdf';
import { toast } from 'sonner';

export default function SupervisorDashboard() {
  const user = useAuthStore((state) => state.user);
  const logout = useAuthStore((state) => state.logout);
  const [captures, setCaptures] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedCapture, setSelectedCapture] = useState<any | null>(null);

  const fetchCaptures = () => {
    fetch('/api/captures')
      .then((res) => res.json())
      .then((data) => {
        // Group by package_id
        const grouped = data.reduce((acc: any, capture: any) => {
          const pkgId = capture.package_id || 'legacy';
          if (!acc[pkgId]) {
            acc[pkgId] = {
              id: pkgId,
              project_name: capture.project_name,
              template_name: capture.template_name || (capture.package_id ? 'Quick Capture' : 'Legacy Capture'),
              user_name: capture.user_name,
              created_at: capture.created_at,
              status: capture.status,
              captures: []
            };
          }
          acc[pkgId].captures.push(capture);
          return acc;
        }, {});
        setCaptures(Object.values(grouped));
        setLoading(false);
      })
      .catch(() => setLoading(false));
  };

  useEffect(() => {
    fetchCaptures();
  }, []);

  const updateStatus = async (id: string, status: string) => {
    const endpoint = id === 'legacy' ? `/api/captures/${id}/status` : `/api/packages/${id}/status`;
    await fetch(endpoint, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status }),
    });
    fetchCaptures();
    if (selectedCapture?.id === id) {
      setSelectedCapture({ ...selectedCapture, status });
    }
    toast.success(`Package marked as ${status}`);
  };

  const generateReport = async () => {
    if (captures.length === 0) {
      toast.error('No captures available to generate a report.');
      return;
    }

    toast.loading('Generating PDF report with images...', { id: 'pdf' });
    
    try {
      const doc = new jsPDF();
      const dateStr = format(new Date(), 'MMM d, yyyy');
      
      doc.setFontSize(22);
      doc.setTextColor(16, 185, 129); // emerald-500
      doc.text(`CIK Daily Jobsite Report`, 14, 22);
      
      doc.setFontSize(12);
      doc.setTextColor(100, 116, 139); // slate-500
      doc.text(`Date: ${dateStr}`, 14, 32);
      doc.text(`Generated by: ${user?.name}`, 14, 38);
      doc.text(`Total Proof Packages: ${captures.length}`, 14, 44);
      
      let yPos = 55;
      
      for (const [index, pkg] of captures.entries()) {
        if (yPos > 240) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setFontSize(16);
        doc.setTextColor(30, 41, 59); // slate-800
        doc.text(`Package #${index + 1}: ${pkg.project_name}`, 14, yPos);
        yPos += 8;
        
        doc.setFontSize(11);
        doc.setTextColor(71, 85, 105); // slate-600
        doc.text(`Template: ${pkg.template_name}`, 14, yPos);
        yPos += 6;
        doc.text(`Worker: ${pkg.user_name} | Time: ${format(new Date(pkg.created_at), 'h:mm a')}`, 14, yPos);
        yPos += 10;

        // Add thumbnails for the first 3 photos in the package
        const photos = pkg.captures.slice(0, 3);
        let xPos = 14;
        for (const capture of photos) {
          if (capture.photo_url) {
            try {
              // Simple image placement - in a real app we'd fetch and convert to base64
              // jsPDF can take a URL if it's on the same origin or has CORS
              doc.addImage(capture.photo_url, 'JPEG', xPos, yPos, 50, 65);
              xPos += 55;
            } catch (e) {
              doc.rect(xPos, yPos, 50, 65);
              doc.text('Image Error', xPos + 10, yPos + 30);
              xPos += 55;
            }
          }
        }
        
        if (photos.length > 0) yPos += 75;
        else yPos += 10;

        doc.setDrawColor(226, 232, 240); // slate-200
        doc.line(14, yPos, 196, yPos);
        yPos += 15;
      }
      
      doc.save(`CIK_Report_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
      toast.success('Report generated with images!', { id: 'pdf' });
    } catch (err) {
      console.error(err);
      toast.error('Failed to generate report.', { id: 'pdf' });
    }
  };

  return (
    <div className="min-h-screen bg-brand-bg flex flex-col md:flex-row text-brand-text">
      {/* Sidebar */}
      <aside className="w-full md:w-64 bg-brand-surface border-r border-brand-border flex flex-col h-auto md:h-screen sticky top-0 z-20">
        <div className="p-6 border-b border-brand-border flex items-center gap-3">
          <div className="w-8 h-8 bg-brand-primary rounded-lg flex items-center justify-center shadow-sm">
            <ImageIcon className="w-4 h-4 text-white" />
          </div>
          <h1 className="font-bold text-brand-text text-lg tracking-tight">CIK Proof</h1>
        </div>
        
        <div className="p-4 flex-1">
          <div className="space-y-1">
            <button className="w-full flex items-center gap-3 px-4 py-2.5 bg-brand-primary/10 text-brand-primary rounded-lg font-medium text-sm transition-colors">
              <FileText className="w-4 h-4" />
              Proof Packages
            </button>
            <button 
              onClick={generateReport}
              className="w-full flex items-center gap-3 px-4 py-2.5 text-brand-text-muted hover:bg-brand-border/50 rounded-lg font-medium text-sm transition-colors mt-2"
            >
              <FileOutput className="w-4 h-4" />
              Generate Daily Report
            </button>
          </div>
        </div>

        <div className="p-4 border-t border-brand-border mt-auto">
          <div className="flex items-center gap-3 mb-4 px-2">
            <div className="w-8 h-8 bg-brand-border rounded-full flex items-center justify-center text-brand-text font-bold text-sm">
              {user?.name?.charAt(0)}
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-semibold text-brand-text truncate">{user?.name}</p>
              <p className="text-xs text-brand-text-muted truncate">Supervisor</p>
            </div>
          </div>
          <button onClick={logout} className="w-full flex items-center justify-center gap-2 px-4 py-2 text-brand-text-muted hover:bg-brand-border/50 rounded-lg text-sm font-medium transition-colors border border-brand-border">
            <LogOut className="w-4 h-4" />
            Sign Out
          </button>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col h-screen overflow-hidden">
        <header className="bg-brand-surface border-b border-brand-border px-8 py-5 flex justify-between items-center shrink-0">
          <h2 className="text-xl font-bold text-brand-text">Proof Packages</h2>
          <div className="flex gap-3">
            <div className="relative">
              <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-brand-text-muted" />
              <input 
                type="text" 
                placeholder="Search worker or project..." 
                className="pl-9 pr-4 py-2 bg-brand-bg border border-brand-border rounded-lg text-sm focus:outline-none focus:ring-1 focus:ring-brand-primary w-64 transition-all text-brand-text placeholder:text-brand-text-muted"
              />
            </div>
            <button className="p-2 border border-brand-border rounded-lg text-brand-text-muted hover:bg-brand-border/50 transition-colors">
              <Filter className="w-4 h-4" />
            </button>
          </div>
        </header>

        <div className="flex-1 overflow-auto p-8 flex gap-8">
          {/* Feed List */}
          <div className="flex-1 space-y-4 max-w-3xl">
            {loading ? (
              <div className="space-y-4">
                {[1, 2, 3].map(i => <div key={i} className="h-32 bg-brand-surface rounded-xl border border-brand-border animate-pulse"></div>)}
              </div>
            ) : captures.length === 0 ? (
              <div className="text-center py-20 text-brand-text-muted">No packages found.</div>
            ) : (
              captures.map(pkg => (
                <div 
                  key={pkg.id} 
                  onClick={() => setSelectedCapture(pkg)}
                  className={`bg-brand-surface rounded-xl border p-4 flex gap-6 cursor-pointer transition-all hover:border-brand-primary/50 ${selectedCapture?.id === pkg.id ? 'border-brand-primary ring-1 ring-brand-primary' : 'border-brand-border'}`}
                >
                  <div className="w-32 h-32 bg-brand-bg rounded-lg overflow-hidden shrink-0 border border-brand-border grid grid-cols-2 gap-0.5">
                    {pkg.captures.slice(0, 4).map((c: any, i: number) => (
                      <img key={i} src={c.photo_url} alt="" className="w-full h-full object-cover" />
                    ))}
                    {pkg.captures.length === 0 && <div className="col-span-2 flex items-center justify-center text-brand-text-muted text-xs">No Photos</div>}
                  </div>
                  
                  <div className="flex-1 flex flex-col justify-between py-1">
                    <div>
                      <div className="flex justify-between items-start mb-1">
                        <h3 className="font-bold text-brand-text text-lg">{pkg.project_name}</h3>
                        <span className={`px-2.5 py-1 rounded-full text-xs font-semibold uppercase tracking-wider
                          ${pkg.status === 'approved' ? 'bg-brand-accent/20 text-brand-accent' : 
                            pkg.status === 'rejected' ? 'bg-brand-danger/20 text-brand-danger' : 
                            'bg-brand-warning/20 text-brand-warning'}`}
                        >
                          {pkg.status}
                        </span>
                      </div>
                      <p className="text-sm text-brand-text-muted font-medium">{pkg.template_name}</p>
                      <div className="flex items-center gap-3 mt-2">
                        <p className="text-sm text-brand-text-muted flex items-center gap-1.5">
                          <span className="w-5 h-5 bg-brand-border rounded-full flex items-center justify-center text-[10px] font-bold text-brand-text">
                            {pkg.user_name?.charAt(0)}
                          </span>
                          {pkg.user_name}
                        </p>
                        <span className="text-xs bg-brand-border/50 px-2 py-0.5 rounded text-brand-text-muted">
                          {pkg.captures.length} Photos
                        </span>
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-4 text-xs text-brand-text-muted font-medium">
                      <span className="flex items-center gap-1.5"><Clock className="w-3.5 h-3.5" /> {format(new Date(pkg.created_at), 'MMM d, yyyy h:mm a')}</span>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Detail Panel */}
          {selectedCapture && (
            <div className="w-96 bg-brand-surface border border-brand-border rounded-xl shadow-sm flex flex-col h-fit sticky top-8 overflow-hidden shrink-0">
              <div className="p-4 border-b border-brand-border flex justify-between items-center bg-brand-bg/50">
                <h3 className="font-bold text-brand-text">Package Details</h3>
                <button onClick={() => setSelectedCapture(null)} className="text-brand-text-muted hover:text-brand-text">
                  <XCircle className="w-5 h-5" />
                </button>
              </div>
              
              <div className="p-4 overflow-y-auto max-h-[calc(100vh-200px)]">
                <div className="space-y-6">
                  {selectedCapture.captures.map((c: any) => (
                    <div key={c.id} className="space-y-3 border-b border-brand-border pb-6 last:border-0">
                      <p className="text-xs font-bold text-brand-primary uppercase tracking-widest">{c.requirement_label || 'Field Proof'}</p>
                      <div className="aspect-[3/4] bg-brand-bg rounded-lg overflow-hidden relative group border border-brand-border">
                        <img src={c.photo_url} alt="" className="w-full h-full object-contain" referrerPolicy="no-referrer" />
                      </div>
                      <div className="grid grid-cols-2 gap-2 text-xs">
                        <div className="bg-brand-bg p-2 rounded border border-brand-border">
                          <p className="text-brand-text-muted mb-0.5">Measurement</p>
                          <p className="font-bold text-brand-text">{c.measurement ? `${c.measurement}${c.unit}` : 'N/A'}</p>
                        </div>
                        <div className="bg-brand-bg p-2 rounded border border-brand-border relative group/loc">
                          <div className="flex justify-between items-start">
                            <p className="text-brand-text-muted mb-0.5">Location</p>
                            {c.latitude && c.longitude && (
                              <div className="flex gap-1 opacity-0 group-hover/loc:opacity-100 transition-opacity">
                                <button 
                                  onClick={() => {
                                    navigator.clipboard.writeText(`${c.latitude}, ${c.longitude}`);
                                    toast.success('Coordinates copied');
                                  }}
                                  className="p-1 hover:bg-brand-primary/10 rounded text-brand-primary"
                                  title="Copy Coordinates"
                                >
                                  <Copy className="w-3 h-3" />
                                </button>
                                <button 
                                  onClick={() => window.open(`https://www.google.com/maps/dir/?api=1&destination=${c.latitude},${c.longitude}`, '_blank')}
                                  className="p-1 hover:bg-brand-primary/10 rounded text-brand-primary"
                                  title="Navigate"
                                >
                                  <Navigation className="w-3 h-3" />
                                </button>
                              </div>
                            )}
                          </div>
                          <p className="font-bold text-brand-text truncate">{c.address}</p>
                        </div>
                      </div>
                      {c.note && (
                        <div className="bg-brand-bg p-2 rounded border border-brand-border text-xs">
                          <p className="text-brand-text-muted mb-0.5">Note</p>
                          <p className="text-brand-text">{c.note}</p>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              <div className="p-4 border-t border-brand-border bg-brand-surface flex gap-3">
                <button 
                  onClick={() => updateStatus(selectedCapture.id, 'rejected')}
                  className={`flex-1 py-2.5 rounded-lg font-medium text-sm transition-colors ${selectedCapture.status === 'rejected' ? 'bg-brand-danger/20 text-brand-danger border border-brand-danger/30' : 'bg-brand-bg border border-brand-border text-brand-text hover:bg-brand-border/50'}`}
                >
                  Reject
                </button>
                <button 
                  onClick={() => updateStatus(selectedCapture.id, 'approved')}
                  className={`flex-1 py-2.5 rounded-lg font-medium text-sm transition-colors flex items-center justify-center gap-2 ${selectedCapture.status === 'approved' ? 'bg-brand-accent text-brand-bg shadow-md shadow-brand-accent/20' : 'bg-brand-accent/10 border border-brand-accent/20 text-brand-accent hover:bg-brand-accent/20'}`}
                >
                  <CheckCircle className="w-4 h-4" />
                  Approve
                </button>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
